import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { CartProvider } from "./context/CartContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
  icons: {
    icon: '/hero.jpg',
    apple: '/hero.jpg',
  },
};

export default function RootLayout({ children }) {


  return (
    // suppressHydrationWarning
    <html lang="en" >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <CartProvider>
        <Header/>
        {children}
        </CartProvider>
        <Footer/>
      </body>
    </html>
  );
}

